name : CICD Pipe line


on:
    push:
        branches:
            - main

jobs:


    job1:
        runs-on: ubuntu-latest
        steps:
            - name: read the file
              uses: actions/checkout@v3
             
            - name : Show Listing
              run: ls