name : CICD OS Release Info

on:
  push:
    branches:
      - main

jobs:
  os_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show OS Release Information
        run: cat /etc/os-release